"""Inspect recordings generated by the actual Live-hosted Gen test device."""
from pathlib import Path
import struct, math, json
ROOT=Path(__file__).resolve().parents[1];AUDIO=ROOT/'docs/verification/audio'
def read(path):
    raw=path.read_bytes();offset=12;fmt=None;payload=None
    while offset+8<=len(raw):
        kind=raw[offset:offset+4];n=struct.unpack_from('<I',raw,offset+4)[0];part=raw[offset+8:offset+8+n]
        if kind==b'fmt ':fmt=struct.unpack_from('<HHIIHH',part)
        if kind==b'data':payload=part
        offset+=8+n+(n&1)
    assert fmt and payload, f'{path.name}: no completed audio data'
    encoding,channels,sr,_,_,bits=fmt
    assert encoding==3 and bits==32 and channels==2, (path.name,fmt)
    vals=struct.unpack('<'+'f'*(len(payload)//4),payload)
    return vals,sr

def rms(a):return math.sqrt(sum(x*x for x in a)/len(a)) if a else 0
results={};fail=[]
for name in [f'mode-{i:02}' for i in range(1,65)]+['midi','restore','freeze','extreme','silence']:
    try:
        a,sr=read(AUDIO/(name+'.wav'));assert all(math.isfinite(v) for v in a),'non-finite samples'
        left=a[0::2];right=a[1::2];peak=max(map(abs,a));level=rms(a)
        r=dict(seconds=round(len(left)/sr,3),sample_rate=sr,peak=round(peak,8),rms=round(level,8),stereo_difference_rms=round(rms([l-r for l,r in zip(left,right)]),8))
        assert peak<=.951,'output exceeded limiter'
        if name=='silence':
            r['settled_peak']=max(map(abs,a[int(.2*sr)*2:]));assert r['settled_peak']<1e-6,'silent mode emitted audio after its release ramp'
        else:assert level>1e-5,'inaudible output'
        if name=='midi':
            r['before_note_rms']=rms(a[int(.2*sr)*2:int(.4*sr)*2]);r['held_note_rms']=rms(a[int(.7*sr)*2:int(2.1*sr)*2]);r['after_note_off_rms']=rms(a[int(2.8*sr)*2:])
            assert r['before_note_rms']<1e-5 and r['held_note_rms']>1e-4 and r['after_note_off_rms']<1e-5,'MIDI gate failure'
        results[name]=r
    except (AssertionError,FileNotFoundError) as e:fail.append(f'{name}: {e}')
summary=dict(scope='Native Gen and controller recordings from Ableton Live; not an original-ROM fidelity comparison.',passed=len(results),failed=fail,recordings=results)
(ROOT/'docs/verification/audio-results.json').write_text(json.dumps(summary,indent=2)+'\n')
print(f'{len(results)}/69 native audio cases passed')
for msg in fail:print(msg)
raise SystemExit(bool(fail))
